# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eschedule.proto\x12\x08schedule\"+\n\x0b\x44\x61ySchedule\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"6\n\x0f\x44\x61yScheduleList\x12#\n\x04list\x18\x01 \x03(\x0b\x32\x15.schedule.DaySchedule\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"!\n\x05Movie\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xeb\x01\n\x08Schedule\x12\x33\n\rAddToSchedule\x12\x0f.schedule.Movie\x1a\x0f.schedule.Empty\"\x00\x12\x38\n\x12RemoveFromSchedule\x12\x0f.schedule.Movie\x1a\x0f.schedule.Empty\"\x00\x12\x36\n\x06GetAll\x12\x0f.schedule.Empty\x1a\x19.schedule.DayScheduleList\"\x00\x12\x38\n\tGetByDate\x12\x0e.schedule.Date\x1a\x19.schedule.DayScheduleList\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DAYSCHEDULE']._serialized_start=28
  _globals['_DAYSCHEDULE']._serialized_end=71
  _globals['_DAYSCHEDULELIST']._serialized_start=73
  _globals['_DAYSCHEDULELIST']._serialized_end=127
  _globals['_DATE']._serialized_start=129
  _globals['_DATE']._serialized_end=149
  _globals['_MOVIE']._serialized_start=151
  _globals['_MOVIE']._serialized_end=184
  _globals['_EMPTY']._serialized_start=186
  _globals['_EMPTY']._serialized_end=193
  _globals['_SCHEDULE']._serialized_start=196
  _globals['_SCHEDULE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
